version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbtemp
    ports:
    - 3306:3306
    volumes:
    - ./db-dump:/docker-entrypoint-initdb.d